#!/usr/bin/env bash
#
# BaeLink - one-shot setup for Windows Subsystem for Linux.
#
# WINDOWS SIDE (once, in an administrator PowerShell - this script cannot do it
# for you, it runs inside Linux):
#
#     wsl --install -d Debian
#     # reboot if prompted, then open the Debian app and create your user
#
# LINUX SIDE (inside the Debian/Ubuntu WSL shell):
#
#     sudo apt update && sudo apt install -y git
#     git clone https://github.com/nigel112/alovoa.git
#     cd alovoa
#     git checkout arena/01a0e2f8-alovoa      # branch with the BaeLink rebrand
#     bash scripts/wsl-setup.sh
#
# What it does:
#   1. installs OpenJDK 17, Maven and MariaDB
#   2. starts MariaDB and creates the alovoa database + user
#   3. writes src/main/resources/application-dev.properties (git-ignored) with
#      the database credentials and freshly generated encryption keys
#   4. builds the jar and starts the server on http://localhost:8080
#
# Options:
#   --build-only   build and generate config, but do not start the server
#   --skip-build   only set up the database and config
#
set -euo pipefail

# Run from the repo root. If the script was downloaded on its own (no repo
# layout next to it), fall back to the directory it was launched from.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[ -f "$REPO_ROOT/pom.xml" ] || REPO_ROOT="$(pwd)"
[ -f "$REPO_ROOT/pom.xml" ] || die "no pom.xml found - run this from the alovoa repository root"
cd "$REPO_ROOT"

DB_NAME="alovoa"
DB_USER="alovoa"
DB_PASS="alovoa"
PROFILE_FILE="src/main/resources/application-dev.properties"
JAR="target/alovoa-1.1.0.jar"
PORT="8080"

BUILD_ONLY=0
SKIP_BUILD=0
for arg in "$@"; do
  case "$arg" in
    --build-only) BUILD_ONLY=1 ;;
    --skip-build) SKIP_BUILD=1 ;;
    -h|--help) sed -n '2,30p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown option: $arg (try --help)"; exit 1 ;;
  esac
done

step() { printf '\n\033[1;36m==> %s\033[0m\n' "$1"; }
info() { printf '    %s\n' "$1"; }
die() { printf '\n\033[1;31merror: %s\033[0m\n' "$1" >&2; exit 1; }

command -v apt-get >/dev/null || die "this script expects Debian or Ubuntu (apt-get not found)"

# ---------------------------------------------------------------- 1. packages
step "Installing OpenJDK 17, Maven and MariaDB"
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -qq
sudo apt-get install -y -qq openjdk-17-jdk maven mariadb-server >/dev/null
info "java:  $(java -version 2>&1 | head -1)"
info "maven: $(mvn -v 2>/dev/null | head -1 || true)"

# ------------------------------------------------------------- 2. the database
step "Starting MariaDB"
# WSL usually has no systemd, so use the service scripts rather than systemctl.
if command -v systemctl >/dev/null && [ -d /run/systemd/system ]; then
  sudo systemctl enable --now mariadb >/dev/null 2>&1 || true
else
  sudo service mariadb start >/dev/null 2>&1 || sudo service mysql start >/dev/null 2>&1 || true
fi
for _ in $(seq 1 30); do
  sudo mysqladmin ping >/dev/null 2>&1 && break
  sleep 1
done
sudo mysqladmin ping >/dev/null 2>&1 || die "MariaDB did not start - check 'sudo service mariadb status'"

step "Creating database '$DB_NAME' and user '$DB_USER'"
sudo mysql -e "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
sudo mysql -e "CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';"
sudo mysql -e "CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASS}';"
sudo mysql -e "GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';"
sudo mysql -e "GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'127.0.0.1';"
sudo mysql -e "FLUSH PRIVILEGES;"
info "database ready"

# --------------------------------------------------------- 3. dev properties
step "Writing $PROFILE_FILE"
if [ -f "$PROFILE_FILE" ]; then
  info "already exists - keeping your current keys and credentials"
else
  # app.text.key must be 16, 24 or 32 bytes (AES); app.text.salt is the IV, so
  # it must be exactly 16 bytes.
  TEXT_KEY="$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32)"
  TEXT_SALT="$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 16)"
  ADMIN_KEY="$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24)"
  REMEMBER_KEY="$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64)"
  cat > "$PROFILE_FILE" <<EOF
# Generated by scripts/wsl-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# This file is git-ignored: it holds local credentials and encryption keys.

spring.datasource.url=jdbc:mariadb://localhost:3306/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Local development has no SMTP server, so do not probe one at startup.
spring.mail.test-connection=false

# AES key (16/24/32 bytes) and initialisation vector (exactly 16 bytes).
app.text.key=${TEXT_KEY}
app.text.salt=${TEXT_SALT}
app.admin.email=admin@localhost
app.admin.key=${ADMIN_KEY}
app.login.remember.key=${REMEMBER_KEY}

app.domain=http://localhost:${PORT}
app.url.front-end=http://localhost:${PORT}
EOF
  info "generated fresh encryption keys (keep this file private)"
fi

# ------------------------------------------------------------------- 4. build
if [ "$SKIP_BUILD" -eq 0 ]; then
  step "Building (first run downloads dependencies and takes a few minutes)"
  mvn -q -DskipTests package
  [ -f "$JAR" ] || die "expected $JAR after the build"
  info "built $JAR"
fi

[ "$BUILD_ONLY" -eq 1 ] && { step "Done (--build-only)"; info "start it with:"; info "  java -jar $JAR --spring.profiles.active=dev"; exit 0; }

# --------------------------------------------------------------------- 5. run
step "Starting BaeLink on http://localhost:${PORT}"
mkdir -p logs
if [ -f logs/app.pid ] && kill -0 "$(cat logs/app.pid)" 2>/dev/null; then
  info "already running with pid $(cat logs/app.pid) - restarting"
  kill "$(cat logs/app.pid)" || true
  sleep 3
fi
nohup java -jar "$JAR" --spring.profiles.active=dev > logs/app.log 2>&1 &
echo $! > logs/app.pid

step "Waiting for the server"
for _ in $(seq 1 60); do
  if curl -fsS "http://localhost:${PORT}/" >/dev/null 2>&1; then
    info "BaeLink is up: http://localhost:${PORT}"
    info "pid $(cat logs/app.pid) - logs: tail -f logs/app.log"
    info "stop it with:  kill \$(cat logs/app.pid)"
    exit 0
  fi
  sleep 2
done

die "server did not answer in time - check logs/app.log (last lines below)\n$(tail -20 logs/app.log)"
